#!/usr/bin/env python3
"""
Build script: reads all PNGs from placeholders/ and writes images-data.js
with base64 data URLs so images work when the app is opened via file:// (no server).
Run once: python build-embed-images.py
Then commit images-data.js so users who open from zip get images.
"""
import base64
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PLACEHOLDERS_DIR = os.path.join(SCRIPT_DIR, "placeholders")
OUT_FILE = os.path.join(SCRIPT_DIR, "images-data.js")

if not os.path.isdir(PLACEHOLDERS_DIR):
    print("placeholders/ folder not found. Run this from the project root.")
    exit(1)

entries = []
for name in sorted(os.listdir(PLACEHOLDERS_DIR)):
    if not name.endswith(".png"):
        continue
    key = "placeholders/" + name
    path = os.path.join(PLACEHOLDERS_DIR, name)
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    data_url = "data:image/png;base64," + b64
    entries.append((key, data_url))

lines = [
    "// Auto-generated by build-embed-images.py or build-embed-images.js — do not edit by hand",
    "// Embeds placeholder images as data URLs so they load on file:// (no server needed)",
    "window.IMAGE_DATA = window.IMAGE_DATA || {};",
] + [
    "window.IMAGE_DATA[" + json.dumps(k) + "] = " + json.dumps(v) + ";"
    for k, v in entries
]

with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Wrote " + OUT_FILE + " (" + str(len(entries)) + " images).")
