// symbols.js
// Auto-generated from newFormat.txt (13x13 layout with blanks).
const symbolGridLayout = [
  [1, null, 2, 3, 4, 5, 6, null, 7, null, 8, 9, 10],
  [11, 12, 13, 14, 15, null, 16, null, 17, 18, 19, 20, 21],
  [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
  [35, 36, 37, 38, 39, null, null, null, 40, 41, 42, 43, 44],
  [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57],
  [58, 59, null, null, 60, null, 61, null, 62, 63, 64, 65, null],
  [66, 67, null, null, 68, null, 69, null, 70, 71, 72, null, null],
  [73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85],
  [86, 87, null, 88, 89, 90, 91, 92, 93, 94, 95, 96, null],
  [97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
  [110, 111, 112, 113, null, null, null, 114, null, 115, 116, 117, null],
  [118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, null],
  [130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142],
];

const symbols = [
  { id: 1, name: "Color", image: "placeholders/color.png", description: "Color, Spectrum, Diverse" },
  { id: 2, name: "Red", image: "placeholders/red.png", description: "Red, Rose, Rust" },
  { id: 3, name: "White", image: "placeholders/white.png", description: "White, Pale, Light Colored" },
  { id: 4, name: "Yellow", image: "placeholders/yellow.png", description: "Yellow, Golden, Caution" },
  { id: 5, name: "Brown", image: "placeholders/brown.png", description: "Brown, Orange, Beige" },
  { id: 6, name: "Gray", image: "placeholders/gray.png", description: "Gray, Ash, Smoke" },
  { id: 7, name: "Blue", image: "placeholders/blue.png", description: "Blue, Green, Cyan" },
  { id: 8, name: "Purple", image: "placeholders/purple.png", description: "Purple, Violet, Pink" },
  { id: 9, name: "Black", image: "placeholders/black.png", description: "Black, Dark, Shadow" },
  { id: 10, name: "Clear", image: "placeholders/clear.png", description: "Clear, Glass, Transparent" },
  { id: 11, name: "State", image: "placeholders/state.png", description: "State, Condition, Attribute" },
  { id: 12, name: "Hard", image: "placeholders/hard.png", description: "Hard, Metal, Rock" },
  { id: 13, name: "Sweet", image: "placeholders/sweet.png", description: "Sweet, Cute, Innocent" },
  { id: 14, name: "Soft", image: "placeholders/soft.png", description: "Soft, Squishy, Fluffy" },
  { id: 15, name: "Hot", image: "placeholders/hot.png", description: "Hot, Heat, Steam" },
  { id: 16, name: "Dirty", image: "placeholders/dirty.png", description: "Dirty, Toxic, Bacteria" },
  { id: 17, name: "Cold", image: "placeholders/cold.png", description: "Cold, Raw, Frozen" },
  { id: 18, name: "New", image: "placeholders/new.png", description: "New, Fresh, Young" },
  { id: 19, name: "Old", image: "placeholders/old.png", description: "Old, Ancient, Aged" },
  { id: 20, name: "Sharp", image: "placeholders/sharp.png", description: "Sharp, Spiky, Jagged" },
  { id: 21, name: "Sticky", image: "placeholders/sticky.png", description: "Sticky, Magnetic, Attract" },
  { id: 22, name: "Shape", image: "placeholders/shape.png", description: "Shape, Outer Layer, Form" },
  { id: 23, name: "Container", image: "placeholders/container.png", description: "Container, Bag, Cup" },
  { id: 24, name: "Hole", image: "placeholders/hole.png", description: "Hole, Entrance, Window" },
  { id: 25, name: "Surface", image: "placeholders/surface.png", description: "Surface, Table, Seat" },
  { id: 26, name: "Flat", image: "placeholders/flat.png", description: "Flat, Paper, Card" },
  { id: 27, name: "Curve", image: "placeholders/curve.png", description: "Curve, Bend, Arch" },
  { id: 28, name: "Cord", image: "placeholders/cord.png", description: "Cord, Hair, Chain" },
  { id: 29, name: "Interlock", image: "placeholders/interlock.png", description: "Interlock, Bond, Connect" },
  { id: 30, name: "Square", image: "placeholders/square.png", description: "Square, Block, Cube" },
  { id: 31, name: "Tilt", image: "placeholders/tilt.png", description: "Tilt, Lean, Slant" },
  { id: 32, name: "Crushed", image: "placeholders/crushed.png", description: "Crushed, Grind, Smash" },
  { id: 33, name: "Round", image: "placeholders/round.png", description: "Round, Circle, Sphere" },
  { id: 34, name: "Stick", image: "placeholders/stick.png", description: "Stick, Rod, Pole" },
  { id: 35, name: "Movement", image: "placeholders/movement.png", description: "Movement, Position, Direction" },
  { id: 36, name: "Above", image: "placeholders/above.png", description: "Above, High, God" },
  { id: 37, name: "Down", image: "placeholders/down.png", description: "Down, Bottom, Humble" },
  { id: 38, name: "Going", image: "placeholders/going.png", description: "Going, Give, Send" },
  { id: 39, name: "Coming Back", image: "placeholders/coming_back.png", description: "Coming Back, Receiving, Transfer" },
  { id: 40, name: "Center", image: "placeholders/center.png", description: "Center, Inside, Midpoint" },
  { id: 41, name: "Right", image: "placeholders/right.png", description: "Right, East, Correct" },
  { id: 42, name: "Arriving", image: "placeholders/arriving.png", description: "Arriving, Future, Becoming" },
  { id: 43, name: "Leaving", image: "placeholders/leaving.png", description: "Leaving, Stealing, Away" },
  { id: 44, name: "Left", image: "placeholders/left.png", description: "Left, West, Wrong" },
  { id: 45, name: "Human", image: "placeholders/human.png", description: "Human, Individual, Person" },
  { id: 46, name: "Head", image: "placeholders/head.png", description: "Head, Leader, Brain" },
  { id: 47, name: "Skin", image: "placeholders/skin.png", description: "Skin, Shell, Leather" },
  { id: 48, name: "Front", image: "placeholders/front.png", description: "Front, Face, Chest" },
  { id: 49, name: "Ear", image: "placeholders/ear.png", description: "Ear, Listen, Attention" },
  { id: 50, name: "Eye", image: "placeholders/eye.png", description: "Eye, See, Observe" },
  { id: 51, name: "Nose", image: "placeholders/nose.png", description: "Nose, Scent, Smell" },
  { id: 52, name: "Mouth", image: "placeholders/mouth.png", description: "Mouth, Taste, Lips" },
  { id: 53, name: "Body", image: "placeholders/body.png", description: "Body, Flesh, Physical State" },
  { id: 54, name: "Arm", image: "placeholders/arm.png", description: "Arm, Hand, Touch" },
  { id: 55, name: "Leg", image: "placeholders/leg.png", description: "Leg, Foot, Knee" },
  { id: 56, name: "Back", image: "placeholders/back.png", description: "Back, Butt, Rear" },
  { id: 57, name: "Bone", image: "placeholders/bone.png", description: "Bone, Tooth, Skeleton" },
  { id: 58, name: "Life", image: "placeholders/life.png", description: "Life, Exist, Living" },
  { id: 59, name: "Plant", image: "placeholders/plant.png", description: "Plant, Vegetation, Bush" },
  { id: 60, name: "Reptile", image: "placeholders/reptile.png", description: "Reptile, Lizard, Turtle" },
  { id: 61, name: "Amphibian", image: "placeholders/amphibian.png", description: "Amphibian, Frog, Salamander" },
  { id: 62, name: "Water Creature", image: "placeholders/water_creature.png", description: "Water Creature, Fish, Shark" },
  { id: 63, name: "Winged Creature", image: "placeholders/winged_creature.png", description: "Winged Creature, Bird, Penguin" },
  { id: 64, name: "Land Animal", image: "placeholders/land_animal.png", description: "Land Animal, Creature, Cattle" },
  { id: 65, name: "Insect", image: "placeholders/insect.png", description: "Insect, Bug, Spider" },
  { id: 66, name: "Food", image: "placeholders/food.png", description: "Food, Edible, Consumable" },
  { id: 67, name: "Spice", image: "placeholders/spice.png", description: "Spice, Extra, Add" },
  { id: 68, name: "Vegetable", image: "placeholders/vegetable.png", description: "Vegetable, Carrot, Onion" },
  { id: 69, name: "Plant Product", image: "placeholders/plant_product.png", description: "Plant Product, Bean, Spider" },
  { id: 70, name: "Drink", image: "placeholders/drink.png", description: "Drink, Milk, Coffee" },
  { id: 71, name: "Fruit", image: "placeholders/fruit.png", description: "Fruit, Apple, Oranges" },
  { id: 72, name: "Mushroom", image: "placeholders/mushroom.png", description: "Mushroom, Fungus, Lichen" },
  { id: 73, name: "Autonomy", image: "placeholders/autonomy.png", description: "Autonomy, Revive, Bring To Life" },
  { id: 74, name: "Creator", image: "placeholders/creator.png", description: "Creator, Parent, Guardian" },
  { id: 75, name: "Cloth", image: "placeholders/cloth.png", description: "Cloth, Fabric, Blanket" },
  { id: 76, name: "Light", image: "placeholders/light.png", description: "Light, Sun, Brignt" },
  { id: 77, name: "Market", image: "placeholders/market.png", description: "Market, Exchange, Buy" },
  { id: 78, name: "Image", image: "placeholders/image.png", description: "Image, Symbol, Picture" },
  { id: 79, name: "Money", image: "placeholders/money.png", description: "Money, Price, Wealth" },
  { id: 80, name: "Medicine", image: "placeholders/medicine.png", description: "Medicine, Band-Aid, Thearpy" },
  { id: 81, name: "Planet", image: "placeholders/planet.png", description: "Planet, Moon, Star" },
  { id: 82, name: "Tool", image: "placeholders/tool.png", description: "Tool, Machine, Device" },
  { id: 83, name: "Road", image: "placeholders/road.png", description: "Road, Method, System" },
  { id: 84, name: "Weapon", image: "placeholders/weapon.png", description: "Weapon, Claw, Knife" },
  { id: 85, name: "Building", image: "placeholders/building.png", description: "Building, Room, House" },
  { id: 86, name: "Matter", image: "placeholders/matter.png", description: "Matter, Thing, Chemical" },
  { id: 87, name: "Earth", image: "placeholders/earth.png", description: "Earth, Nature, World" },
  { id: 88, name: "Fluid", image: "placeholders/fluid.png", description: "Fluid, Water, Liquid" },
  { id: 89, name: "Fire", image: "placeholders/fire.png", description: "Fire, Cooked, Baked" },
  { id: 90, name: "Semi Solid", image: "placeholders/semi_solid.png", description: "Semi Solid, Powder, Paste" },
  { id: 91, name: "Time", image: "placeholders/time.png", description: "Time, Date, Hour" },
  { id: 92, name: "Sound", image: "placeholders/sound.png", description: "Sound, Music, Voice" },
  { id: 93, name: "Reflect", image: "placeholders/reflect.png", description: "Reflect, Duplicate, Echo" },
  { id: 94, name: "Electricity", image: "placeholders/electricity.png", description: "Electricity, Lightning, Thunder" },
  { id: 95, name: "Gravity", image: "placeholders/gravity.png", description: "Gravity, Fall, Inertia" },
  { id: 96, name: "Gas", image: "placeholders/gas.png", description: "Gas, Air, Atmosphere" },
  { id: 97, name: "Emotion", image: "placeholders/emotion.png", description: "Emotion, Heart, Sense" },
  { id: 98, name: "Strong", image: "placeholders/strong.png", description: "Strong, Confident, Powerful" },
  { id: 99, name: "Sexy", image: "placeholders/sexy.png", description: "Sexy, Copulate, Lust" },
  { id: 100, name: "Positive", image: "placeholders/positive.png", description: "Positive, Good, Useful" },
  { id: 101, name: "Surprise", image: "placeholders/surprise.png", description: "Surprise, Amazing, Cool" },
  { id: 102, name: "Aggressive", image: "placeholders/aggressive.png", description: "Aggressive, Challenge, Passion" },
  { id: 103, name: "Strange", image: "placeholders/strange.png", description: "Strange, Crazy, Silly" },
  { id: 104, name: "Wishful", image: "placeholders/wishful.png", description: "Wishful, Need, Should" },
  { id: 105, name: "Embarrassment", image: "placeholders/embarrassment.png", description: "Embarrassment, Guilt, Dishonor" },
  { id: 106, name: "Playful", image: "placeholders/playful.png", description: "Playful, Art, Comedy" },
  { id: 107, name: "Painful", image: "placeholders/painful.png", description: "Painful, Suffering, Depression" },
  { id: 108, name: "Negative", image: "placeholders/negative.png", description: "Negative, Evil, Bad" },
  { id: 109, name: "Fearful", image: "placeholders/fearful.png", description: "Fearful, Scary, Monster" },
  { id: 110, name: "Name", image: "placeholders/name.png", description: "Name, Word, Title" },
  { id: 111, name: "I", image: "placeholders/i.png", description: "I, My, Myself" },
  { id: 112, name: "We", image: "placeholders/we.png", description: "We, Our, Together" },
  { id: 113, name: "You", image: "placeholders/you.png", description: "You, Your, Yourself" },
  { id: 114, name: "They", image: "placeholders/they.png", description: "They, Them, Others" },
  { id: 115, name: "He", image: "placeholders/he.png", description: "He, His, Husband" },
  { id: 116, name: "She", image: "placeholders/she.png", description: "She, Hers, Wife" },
  { id: 117, name: "Dead", image: "placeholders/dead.png", description: "Dead, Dying, Birth" },
  { id: 118, name: "Group", image: "placeholders/group.png", description: "Group, Community, Class" },
  { id: 119, name: "Same", image: "placeholders/same.png", description: "Same, Similar, Sibilling" },
  { id: 120, name: "Two", image: "placeholders/two.png", description: "Two, Pair, Both" },
  { id: 121, name: "All", image: "placeholders/all.png", description: "All, Every, Universe" },
  { id: 122, name: "Bump", image: "placeholders/bump.png", description: "Bump, Pile, Hill" },
  { id: 123, name: "Dot", image: "placeholders/dot.png", description: "Dot, Line, Brush" },
  { id: 124, name: "One", image: "placeholders/one.png", description: "One, Mix, Unite" },
  { id: 125, name: "Many", image: "placeholders/many.png", description: "Many, Quantity, Most" },
  { id: 126, name: "Numbers", image: "placeholders/numbers.png", description: "Numbers, Count, Score" },
  { id: 127, name: "Small", image: "placeholders/small.png", description: "Small, Few, Bearly" },
  { id: 128, name: "Big", image: "placeholders/big.png", description: "Big, Heavy, Grow" },
  { id: 129, name: "Zero", image: "placeholders/zero.png", description: "Zero, No, Not" },
  { id: 130, name: "Change", image: "placeholders/change.png", description: "Change, Different, Edit" },
  { id: 131, name: "Believe", image: "placeholders/believe.png", description: "Believe, Know, Plan" },
  { id: 132, name: "Allow", image: "placeholders/allow.png", description: "Allow, Able, Can" },
  { id: 133, name: "Start", image: "placeholders/start.png", description: "Start, Origin, Launch" },
  { id: 134, name: "Decieve", image: "placeholders/decieve.png", description: "Decieve, Pretend, Lie" },
  { id: 135, name: "Cut", image: "placeholders/cut.png", description: "Cut, Seperate, Divide" },
  { id: 136, name: "Prevent", image: "placeholders/prevent.png", description: "Prevent, Stop, Limit" },
  { id: 137, name: "Remove", image: "placeholders/remove.png", description: "Remove, Break, Kill" },
  { id: 138, name: "Resting", image: "placeholders/resting.png", description: "Resting, Lazy, Absent" },
  { id: 139, name: "Make", image: "placeholders/make.png", description: "Make, Create, Produce" },
  { id: 140, name: "Wait", image: "placeholders/wait.png", description: "Wait, Safe, Protect" },
  { id: 141, name: "End", image: "placeholders/end.png", description: "End, Completed, Ago" },
  { id: 142, name: "Fight", image: "placeholders/fight.png", description: "Fight, Push, Hit" },
];
