// symbols.js
// List of 140 symbols for the create page (ids 1-140 continuous; former 64-70 duplicate colors removed)
// Each symbol has an id, name, image (or rgb for colors), and a 3-word description you can edit later

const symbols = [
  { id: 1, name: "cold", image: "placeholders/cold.png", description: "cold, raw, frozen, ice, snow" },
  { id: 2, name: "water", image: "placeholders/water.png", description: "water, liquid, fluid, pool, lake" },
  { id: 3, name: "semi solid", image: "placeholders/semi_solid.png", description: "semi solid, paste, powder, goo" },
  { id: 4, name: "earth", image: "placeholders/earth.png", description: "earth, land, soil, nature, world" },
  { id: 5, name: "hard object", image: "placeholders/hard_object.png", description: "hard object, metal, rock, plastic" },
  { id: 6, name: "brick", image: "placeholders/brick.png", description: "brick, cube, square, block" },
  { id: 7, name: "crushed", image: "placeholders/crushed.png", description: "crushed, grind, smash" },
  { id: 8, name: "spice", image: "placeholders/spice.png", description: "spice, add, extra, fancy" },
  { id: 9, name: "mushroom", image: "placeholders/mushroom.png", description: "mushroom, fungus, lichen" },
  { id: 10, name: "dirty", image: "placeholders/dirty.png", description: "dirty, toxic, gross, bacteria" },
  { id: 11, name: "plant", image: "placeholders/plant.png", description: "plant, vegetation, leaf, bush" },
  { id: 12, name: "fruit", image: "placeholders/fruit.png", description: "fruit, veg, bean, nut" },
  { id: 13, name: "light", image: "placeholders/light.png", description: "sun, light, bright, shine, solar" },
  { id: 14, name: "fire", image: "placeholders/fire.png", description: "hot, fire, fuel, bake, flame" },
  { id: 15, name: "electricity", image: "placeholders/electricity.png", description: "electricity, thunder, lightning" },
  { id: 16, name: "magnetic", image: "placeholders/magnetic.png", description: "sticky, magnetic, attract" },
  { id: 17, name: "air", image: "placeholders/air.png", description: "air, spirit, atmosphere, gas" },
  { id: 18, name: "fluffy", image: "placeholders/fluffy.png", description: "fluffy, soft, squishy" },
  { id: 19, name: "moon", image: "placeholders/moon.png", description: "moon, night sky, star, planet" },
  { id: 20, name: "music", image: "placeholders/music.png", description: "music, scream, sound, voice" },
  { id: 21, name: "image", image: "placeholders/image.png", description: "image, picture, symbol, photo" },
  { id: 22, name: "flat", image: "placeholders/flat.png", description: "flat, paper, book, card, site" },
  { id: 23, name: "wealth", image: "placeholders/wealth.png", description: "money, wealth, price, trezure" },
  { id: 24, name: "cloth", image: "placeholders/cloth.png", description: "cloth, fabric, blanket, cover" },
  { id: 25, name: "market", image: "placeholders/market.png", description: "market, shop, buy, deal, trade" },
  { id: 26, name: "tool", image: "placeholders/tool.png", description: "tool, machine, device" },
  { id: 27, name: "chain", image: "placeholders/chain.png", description: "chain, cord, hair, rope, yarn" },
  { id: 28, name: "stick", image: "placeholders/stick.png", description: "stick, rod, stick, beam, pole" },
  { id: 29, name: "plant product", image: "placeholders/plant_product.png", description: "plant product, corn, oat, rice" },
  { id: 30, name: "container", image: "placeholders/container.png", description: "container, box, bag, cup, jar" },
  { id: 31, name: "medicine", image: "placeholders/medicine.png", description: "medicine, pill, bandaid, thearpy" },
  { id: 32, name: "house", image: "placeholders/house.png", description: "house, room facility, building" },
  { id: 33, name: "door", image: "placeholders/door.png", description: "door, hole, window, entrance" },
  { id: 34, name: "table", image: "placeholders/table.png", description: "table, seat, horizontal, surface," },
  { id: 35, name: "wheel", image: "placeholders/wheel.png", description: "wheel, round, circle, shpere" },
  { id: 36, name: "weapon", image: "placeholders/weapon.png", description: "weapon, arrow, knife, claw" },
  { id: 37, name: "community", image: "placeholders/community.png", description: "community, group, tribe, class" },
  { id: 38, name: "parent", image: "placeholders/parent.png", description: "parent, creator, care taker" },
  { id: 39, name: "human", image: "placeholders/human.png", description: "human, person, individual" },
  { id: 40, name: "name", image: "placeholders/name.png", description: "name, word, brand, label, title" },
  { id: 41, name: "you", image: "placeholders/you.png", description: "you, your, yourself" },
  { id: 42, name: "I", image: "placeholders/i.png", description: "I me, we, us, out, self" },
  { id: 43, name: "male", image: "placeholders/male.png", description: "man, him, his, husband" },
  { id: 44, name: "female", image: "placeholders/female.png", description: "female, she, hers, wife" },
  { id: 45, name: "head", image: "placeholders/head.png", description: "head, guide, brain,  ruler" },
  { id: 46, name: "skin", image: "placeholders/skin.png", description: "skin, outer layer, shape, form" },
  { id: 47, name: "face", image: "placeholders/face.png", description: "face, front, chest, ahead" },
  { id: 48, name: "ear", image: "placeholders/ear.png", description: "ear, listen, attention, obey" },
  { id: 49, name: "eye", image: "placeholders/eye.png", description: "eye, observe, see, examine" },
  { id: 50, name: "mouth", image: "placeholders/mouth.png", description: "mouth, lips, jaw, kiss, bite" },
  { id: 51, name: "heart", image: "placeholders/heart.png", description: "heart, feeling, emotion, mood" },
  { id: 52, name: "body", image: "placeholders/body.png", description: "body, flesh, physical state" },
  { id: 53, name: "bone", image: "placeholders/bone.png", description: "bone, tooth, skeleton" },
  { id: 54, name: "arm", image: "placeholders/arm.png", description: "arm, hand, tap, touch, gesture" },
  { id: 55, name: "foot", image: "placeholders/foot.png", description: "foot, leg, heel, kick, knee" },
  { id: 56, name: "bug", image: "placeholders/bug.png", description: "bug, insect, ant, spider" },
  { id: 57, name: "reptile", image: "placeholders/reptile.png", description: "reptile, amphibian, ugly animal" },
  { id: 58, name: "land animal", image: "placeholders/land_animal.png", description: "land animal, beast, creature" },
  { id: 59, name: "water creature", image: "placeholders/water_creature.png", description: "water creature, fish" },
  { id: 60, name: "winged animal", image: "placeholders/winged_animal.png", description: "winged/flying creature, bird" },
  { id: 61, name: "thing", image: "placeholders/thing.png", description: "thing, entity, chemical, matter" },
  { id: 62, name: "dead", image: "placeholders/dead.png", description: "dead, dying, kill, execution" },
  { id: 63, name: "color", image: "placeholders/color.png", description: "color, spectrum, diverse" },
  { id: 64, name: "aggressive", image: "placeholders/aggressive.png", description: "aggressive, assault, challenge" },
  { id: 65, name: "evil", image: "placeholders/evil.png", description: "bad, evil, negative, choas" },
  { id: 66, name: "sharp", image: "placeholders/sharp.png", description: "spiky, sharp" },
  { id: 67, name: "scary", image: "placeholders/scary.png", description: "Fearful, scary, monster" },
  { id: 68, name: "guilty", image: "placeholders/guilty.png", description: "guilty, dishonor, embarrass" },
  { id: 69, name: "changed", image: "placeholders/changed.png", description: "different, changed, modify, edit" },
  { id: 70, name: "good", image: "placeholders/good.png", description: "good, positive, useful, friendly" },
  { id: 71, name: "sweet", image: "placeholders/sweet.png", description: "sweet, cute,  innocent, candy" },
  { id: 72, name: "small", image: "placeholders/small.png", description: "small, few, barely" },
  { id: 73, name: "new", image: "placeholders/new.png", description: "new, fresh, young, modern" },
  { id: 74, name: "epic", image: "placeholders/epic.png", description: "epic, cool, amazing" },
  { id: 75, name: "strong", image: "placeholders/strong.png", description: "strong, powerful, confident" },
  { id: 76, name: "big", image: "placeholders/big.png", description: "big, heavy, large, expand, grow" },
  { id: 77, name: "unusual", image: "placeholders/unusual.png", description: "unusual, strange, crazy, silly" },
  { id: 78, name: "old", image: "placeholders/old.png", description: "old, aged, ancient" },
  { id: 79, name: "method", image: "placeholders/method.png", description: "method, system, road, course" },
  { id: 80, name: "atomony", image: "placeholders/atomony.png", description: "atomony, bring to life" },
  { id: 81, name: "stand", image: "placeholders/stand.png", description: "stand, protect, safe, wait" },
  { id: 82, name: "play", image: "placeholders/play.png", description: "play, art, comedy, entertain" },
  { id: 83, name: "sexy", image: "placeholders/sexy.png", description: "sexy, sexual relations with" },
  { id: 84, name: "sleeping", image: "placeholders/sleeping.png", description: "sleeping, resting, lazy, laying" },
  { id: 85, name: "dot", image: "placeholders/dot.png", description: "dot, line, drawing, brush" },
  { id: 86, name: "allow", image: "placeholders/allow.png", description: "able, allow, can, may, could" },
  { id: 87, name: "start", image: "placeholders/start.png", description: "start, begin, launch, origin" },
  { id: 88, name: "one", image: "placeholders/one.png", description: "one, unite, mix, combine, blend" },
  { id: 89, name: "bump", image: "placeholders/bump.png", description: "bumb, pile, hill, pertrusion" },
  { id: 90, name: "two", image: "placeholders/two.png", description: "two, pair, double, both" },
  { id: 91, name: "going", image: "placeholders/going.png", description: "going to, toward, for, motion" },
  { id: 92, name: "bond", image: "placeholders/bond.png", description: "bond, braid, interlock, connect" },
  { id: 93, name: "many", image: "placeholders/many.png", description: "many, several, quantity, most" },
  { id: 94, name: "arriving", image: "placeholders/arriving.png", description: "arriving, future, to become" },
  { id: 95, name: "same", image: "placeholders/same.png", description: "same, similar, sibling, peer" },
  { id: 96, name: "numbers", image: "placeholders/numbers.png", description: "numbers, count, rank, score" },
  { id: 97, name: "must", image: "placeholders/must.png", description: "must, need, should, want, wish" },
  { id: 98, name: "all", image: "placeholders/all.png", description: "all, every, life, universe" },
  { id: 99, name: "absent", image: "placeholders/absent.png", description: "absent, eliminate, ban, leave" },
  { id: 100, name: "false", image: "placeholders/false.png", description: "false, lie, pretend, deceive" },
  { id: 101, name: "stop", image: "placeholders/stop.png", description: "stop, limit, halt, prevent" },
  { id: 102, name: "zero", image: "placeholders/zero.png", description: "no, not, zero" },
  { id: 103, name: "end", image: "placeholders/end.png", description: "(end, result, completed, ago" },
  { id: 104, name: "back", image: "placeholders/back.png", description: "back, behind, rear, butt" },
  { id: 105, name: "down", image: "placeholders/down.png", description: "down, below, bottom, humble" },
  { id: 106, name: "left", image: "placeholders/left.png", description: "left side" },
  { id: 107, name: "right", image: "placeholders/right.png", description: "right side" },
  { id: 108, name: "center", image: "placeholders/center.png", description: "center, inside, between, midpoint, present, ordinary" },
  { id: 109, name: "above", image: "placeholders/above.png", description: "above, high, god, divine" },
  { id: 110, name: "reflect", image: "placeholders/reflect.png", description: "reflect, echo, duplicate" },
  { id: 111, name: "tilt", image: "placeholders/tilt.png", description: "tilt, slant, lean" },
  { id: 112, name: "time", image: "placeholders/time.png", description: "time, hour, date, movement" },
  { id: 113, name: "bend", image: "placeholders/bend.png", description: "bow, bend, arch, curve" },
  // Colors 114–140: rgb scale 0→0, 50→128, 100→255
  { id: 114, name: "black", rgb: [0, 0, 0], description: "black" },
  { id: 115, name: "navy", rgb: [0, 0, 128], description: "navy blue" },
  { id: 116, name: "blue", rgb: [0, 0, 255], description: "blue" },
  { id: 117, name: "forest", rgb: [0, 128, 0], description: "forest green" },
  { id: 118, name: "teal", rgb: [0, 128, 128], description: "teal" },
  { id: 119, name: "azure", rgb: [0, 128, 255], description: "azure" },
  { id: 120, name: "green", rgb: [0, 255, 0], description: "green" },
  { id: 121, name: "mint", rgb: [0, 255, 128], description: "mint" },
  { id: 122, name: "cyan", rgb: [0, 255, 255], description: "cyan" },
  { id: 123, name: "crimson", rgb: [128, 0, 0], description: "crimson" },
  { id: 124, name: "plum", rgb: [128, 0, 128], description: "plum" },
  { id: 125, name: "purple", rgb: [128, 0, 255], description: "purple" },
  { id: 126, name: "olive", rgb: [128, 128, 0], description: "olive" },
  { id: 127, name: "gray", rgb: [128, 128, 128], description: "gray" },
  { id: 128, name: "periwinkle", rgb: [128, 128, 255], description: "periwinkle" },
  { id: 129, name: "lime", rgb: [128, 255, 0], description: "lime" },
  { id: 130, name: "emerald", rgb: [128, 255, 128], description: "emerald" },
  { id: 131, name: "turquoise", rgb: [128, 255, 255], description: "turquoise" },
  { id: 132, name: "red", rgb: [255, 0, 0], description: "red" },
  { id: 133, name: "rose", rgb: [255, 0, 128], description: "rose" },
  { id: 134, name: "magenta", rgb: [255, 0, 255], description: "magenta" },
  { id: 135, name: "orange", rgb: [255, 128, 0], description: "orange" },
  { id: 136, name: "peach", rgb: [255, 128, 128], description: "peach" },
  { id: 137, name: "pink", rgb: [255, 128, 255], description: "pink" },
  { id: 138, name: "yellow", rgb: [255, 255, 0], description: "yellow" },
  { id: 139, name: "butter", rgb: [255, 255, 128], description: "butter" },
  { id: 140, name: "white", rgb: [255, 255, 255], description: "white" }
];
